name: ros2_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - ca-certificates
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libstdcxx-ng
  - ncurses
  - openssl
  - pip
  - python=3.12
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pytorch-cpu
  - pip:
    - numpy<2.0
    - matplotlib
    - sympy
    - scipy
    - pandas
    - scikit-learn
    - tk
    - empy
    - tqdm
    - catkin-pkg
    - pyyaml